# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TR Proficient Tech Services
email: tomasrossi264@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Step into the future of cybersecurity with TR Proficient Tech Services, where innovation and expertise converge to protect your digital assets. As leaders in the cybersecurity realm, we offer a suite of specialized services designed to fortify your organization against the ever-evolving threat landscape. Our elite pentesting methodologies simulate sophisticated cyber attacks to identify weaknesses, ensuring your defenses are battle-ready.

  Delve deeper with our comprehensive vulnerability assessments, where our seasoned experts meticulously scrutinize your systems to unearth vulnerabilities and provide actionable insights for remediation. Our state-of-the-art Security Operations Center (SOC) stands as your vigilant sentinel, offering round-the-clock monitoring and rapid response capabilities to neutralize threats in real-time.

  At the heart of our defense strategy is Continuous Vulnerability Management (CVM), a proactive approach that keeps your security posture resilient against new vulnerabilities with ongoing assessment and immediate response mechanisms.

  Partnering with TR Proficient Tech Services means more than just enhancing your security measures; it's about embracing a culture of cybersecurity awareness and resilience. Let us tailor a fortress of protection around your digital landscape, ensuring your business thrives in a secure, uninterrupted environment."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://trproficienttechservices.link" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tomasr264
github_username:  TomasR264

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
